version: "2"
networks:
  dev:
    driver: bridge
services:
  admin-server:
    container_name: admin-server
    image: dagrawal/spring-boot-admin-server
    environment:
      SPRING_PROFILES_ACTIVE: insecure
    ports:
      - 9090:9090
    networks:
      - dev
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - dev
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ADVERTISED_HOST_NAME: 192.168.128.190
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 10000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev
  kafka-manager:
    container_name: kafka-manager
    image: sheepkiller/kafka-manager
    environment: 
       ZK_HOSTS: zookeeper:2181
       APPLICATION_SECRET: letmein
    ports:
      - 9000:9000
    networks:
      - dev
   